// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axjmrhmxuppnzywzhzgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4am1yaG14dXBwbnp5d3poemdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3MzE4NDQsImV4cCI6MjA5MDMwNzg0NH0.SH3DdlzGP9rq9t63P0FY6fiQAMqYZp8jY03vyZbP6u0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});